russian_map = {
    'measurement':'Измерение',
    'measurement_id': 'Номер измерения',
    'value': 'Значение',
    'measurement_type' : 'Тип измерения',
    'measurement_type_id' : 'Номер типа измерения',
    'measurement_type_name': 'Название типа измерения',
    'pdk': 'ПДК',
    'is_weather_condition': 'Погодные условия',
    'measurement_unit': 'Единица измерения',
    'measurement_unit_id': 'Номер единицы измерения',
    'measurement_unit_name': 'Название единицы измерения',
    'organization': 'Организация',
    'organization_id': 'Номер организации',
    'organization_name': 'Название организации',
    'point': 'Точка на карте',
    'point_id': 'Номер точки',
    'name': 'Название точки',
    'latitude': 'Широта',
    'longitude': 'Долгота',
    'point_type': 'Тип точки',
    'point_type_id': 'Номер типа точек',
    'point_type_name': 'Название типа точек',
    'position': 'Должность',
    'position_id': 'Номер должности',
    'position_name': 'Название должности',
    'try': 'Проба'
    'try_id': 'Номер пробы',
    'start_time': 'Начало отбора',
    'is_public': 'Публичность',
    'duration': 'Длительность отбора',
    'cicle_number': 'Номер прохода',
    'user': 'Пользователь'
    'user_id': 'Номер пользователя',
    'login': 'Логин',
    'password_hash': 'Хэш пароля',
    'fio': 'ФИО',
    'user_type': 'Тип пользователя',
    'type_id': 'Номер типа',
    'type_name': 'Название типа'
    }
